using Ballastlane.Domain.Exceptions;
using Ballastlane.Domain.ValueObjects;

namespace Ballastlane.Domain.Entities;

/// <summary>
/// Aggregate root — User.
/// Pattern: Entity with private setters enforcing invariants via constructor.
/// SOLID: SRP — holds user identity and credential facts; no auth logic here (belongs to Application).
/// </summary>
public class User
{
    public Guid Id { get; private set; }
    public string Username { get; private set; }
    public Email Email { get; private set; }

    /// <summary>PBKDF2 / Argon2 hash stored as Base64.</summary>
    public string PasswordHash { get; private set; }

    /// <summary>Random salt stored as Base64, generated by the auth service.</summary>
    public string Salt { get; private set; }

    public string Role { get; private set; }

    public User(
        Guid id,
        string username,
        Email email,
        string passwordHash,
        string salt,
        string role = "User")
    {
        if (id == Guid.Empty)
            throw new DomainException("User id must not be empty.");
        if (string.IsNullOrWhiteSpace(username))
            throw new DomainException("Username is required.");
        if (string.IsNullOrWhiteSpace(passwordHash))
            throw new DomainException("PasswordHash is required.");
        if (string.IsNullOrWhiteSpace(salt))
            throw new DomainException("Salt is required.");

        Id = id;
        Username = username.Trim();
        Email = email ?? throw new DomainException("Email is required.");
        PasswordHash = passwordHash;
        Salt = salt;
        Role = role ?? "User";
    }

    /// <summary>Domain operation — updates mutable profile fields.</summary>
    public void UpdateProfile(string username, Email email)
    {
        if (string.IsNullOrWhiteSpace(username))
            throw new DomainException("Username is required.");

        Username = username.Trim();
        Email = email ?? throw new DomainException("Email is required.");
    }
}
